# Config Postgres Pod
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: prod-app
      tier: postgres
  template:
    metadata:
      labels:
	app: prod-app
        tier: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        envFrom:
          - configMapRef:
              name: postgres-config
        ports:
	- containerPort: 5432
          name: postgredb
        volumeMounts:
        - name: postgredb
          mountPath: /var/lib/postgresql
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgredb
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi
# Config Service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: prod-app
    tier: postgres
data:
  POSTGRES_DB: news
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: prod-app
    tier: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
    app: prod-app
    tier: postgres
# Config PersistentVolume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-prod
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.0.32
    path: /home/nfs
