# Config Pod with volume
apiVersion: v1
kind: Pod
metadata:
  name: stage-vol
spec:
  containers:
    - name: frontend-nginx
      image: nginx
      volumeMounts:
        - mountPath: "/tmp/static"
          name: static
    - name: backend-nginx
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/tmp/cache"
          name: static
  volumes:
    - name: static
      emptyDir: {}
