resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [master]
    master-1.ru-central1.internal ansible_host=${yandex_compute_instance.master-1.network_interface.0.nat_ip_address}
 
    [nodes]
    node-1.ru-central1.internal ansible_host=${yandex_compute_instance.node-1.network_interface.0.nat_ip_address}
    node-2.ru-central1.internal ansible_host=${yandex_compute_instance.node-2.network_interface.0.nat_ip_address}
    node-3.ru-central1.internal ansible_host=${yandex_compute_instance.node-3.network_interface.0.nat_ip_address}

    [jenkinsmaster]
    jenkins-master-01.ru-central1.internal ansible_host=${yandex_compute_instance.jenkins-master01.network_interface.0.nat_ip_address}
  
    [jenkinsagent]
    jenkins-agent-01.ru-central1.internal ansible_host=${yandex_compute_instance.jenkins-agent01.network_interface.0.nat_ip_address}

    DOC
  filename = "./ansible/inventory.ini"

  depends_on = [
    yandex_compute_instance.master,
    yandex_compute_instance.node,
    yandex_compute_instance.jenkins-master01,
    yandex_compute_instance.jenkins-agent01
  ]
}
