resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [master]
    master01.ru-central1.internal ansible_host=${yandex_compute_instance.master01.network_interface.0.nat_ip_address}
 
    [nodes]
    node01.ru-central1.internal ansible_host=${yandex_compute_instance.node01.network_interface.0.nat_ip_address}
    node02.ru-central1.internal ansible_host=${yandex_compute_instance.node02.network_interface.0.nat_ip_address}
    node03.ru-central1.internal ansible_host=${yandex_compute_instance.node03.network_interface.0.nat_ip_address}

    [jenkinsmaster]
    jenkins-master-01.ru-central1.internal ansible_host=${yandex_compute_instance.jenkins-master01.network_interface.0.nat_ip_address}
  
    [jenkinsagent]
    jenkins-agent-01.ru-central1.internal ansible_host=${yandex_compute_instance.jenkins-agent01.network_interface.0.nat_ip_address}

    DOC
  filename = "./ansible/inventory.ini"

  depends_on = [
    yandex_compute_instance.master01,
    yandex_compute_instance.node01,
    yandex_compute_instance.node02,
    yandex_compute_instance.node03,
    yandex_compute_instance.jenkins-master01,
    yandex_compute_instance.jenkins-agent01
  ]
}
