---
all:
  hosts:
    jenkins-master:
      ansible_host: 178.154.205.190
    jenkins-agent:
      ansible_host: 178.154.200.49
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master:
        jenkins_agents:
          hosts:
              jenkins-agent:
  vars:
    ansible_connection_type: paramiko
    ansible_user: devops
