## qbec.yaml

apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: <имя проекта Qbec>
spec:
  environments:
    stage:
      defaultNamespace: <имя namespace>
      server: https://127.0.0.1:6443
  vars:
    external:
      - name: image_tag
        default: latest
